const protocols = [
  // ================= APPLICATION LAYER =================
  {
    name: "HTTP",
    full: "HyperText Transfer Protocol",
    layer: "Application",
    ports: "80 / 443",
    desc: "Web communication protocol for websites and APIs.",
    img: "https://via.placeholder.com/400x250?text=HTTP",
  },
  {
    name: "HTTPS",
    full: "HTTP Secure (TLS encrypted HTTP)",
    layer: "Application",
    ports: "443",
    desc: "Secure version of HTTP using TLS encryption.",
    img: "https://via.placeholder.com/400x250?text=HTTPS",
  },
  {
    name: "DNS",
    full: "Domain Name System",
    layer: "Application",
    ports: "53",
    desc: "Translates domain names into IP addresses.",
    img: "https://via.placeholder.com/400x250?text=DNS",
  },
  {
    name: "DHCP",
    full: "Dynamic Host Configuration Protocol",
    layer: "Application",
    ports: "67 / 68",
    desc: "Automatically assigns IP addresses to devices.",
    img: "https://via.placeholder.com/400x250?text=DHCP",
  },
  {
    name: "FTP",
    full: "File Transfer Protocol",
    layer: "Application",
    ports: "21 / 20",
    desc: "Transfers files between systems.",
    img: "https://via.placeholder.com/400x250?text=FTP",
  },
  {
    name: "SFTP",
    full: "Secure File Transfer Protocol (SSH-based)",
    layer: "Application",
    ports: "22",
    desc: "Secure file transfer over encrypted SSH tunnel.",
    img: "https://via.placeholder.com/400x250?text=SFTP",
  },
  {
    name: "SMTP",
    full: "Simple Mail Transfer Protocol",
    layer: "Application",
    ports: "25 / 587",
    desc: "Sends emails between mail servers.",
    img: "https://via.placeholder.com/400x250?text=SMTP",
  },
  {
    name: "IMAP",
    full: "Internet Message Access Protocol",
    layer: "Application",
    ports: "143 / 993",
    desc: "Syncs emails directly from server.",
    img: "https://via.placeholder.com/400x250?text=IMAP",
  },
  {
    name: "POP3",
    full: "Post Office Protocol v3",
    layer: "Application",
    ports: "110 / 995",
    desc: "Downloads emails locally.",
    img: "https://via.placeholder.com/400x250?text=POP3",
  },
  {
    name: "SNMP",
    full: "Simple Network Management Protocol",
    layer: "Application",
    ports: "161 / 162",
    desc: "Network device monitoring and management.",
    img: "https://via.placeholder.com/400x250?text=SNMP",
  },
  {
    name: "LDAP",
    full: "Lightweight Directory Access Protocol",
    layer: "Application",
    ports: "389 / 636",
    desc: "Directory services for authentication systems.",
    img: "https://via.placeholder.com/400x250?text=LDAP",
  },

  // ================= TRANSPORT LAYER =================
  {
    name: "TCP",
    full: "Transmission Control Protocol",
    layer: "Transport",
    ports: "Various",
    desc: "Reliable, connection-based data transmission.",
    img: "https://via.placeholder.com/400x250?text=TCP",
  },
  {
    name: "UDP",
    full: "User Datagram Protocol",
    layer: "Transport",
    ports: "Various",
    desc: "Fast, connectionless data transmission.",
    img: "https://via.placeholder.com/400x250?text=UDP",
  },
  {
    name: "QUIC",
    full: "Quick UDP Internet Connections",
    layer: "Transport",
    ports: "443",
    desc: "Modern transport protocol used by HTTP/3.",
    img: "https://via.placeholder.com/400x250?text=QUIC",
  },

  // ================= NETWORK LAYER =================
  {
    name: "IP",
    full: "Internet Protocol",
    layer: "Network",
    ports: "N/A",
    desc: "Core protocol for addressing and routing packets.",
    img: "https://via.placeholder.com/400x250?text=IP",
  },
  {
    name: "ICMP",
    full: "Internet Control Message Protocol",
    layer: "Network",
    ports: "N/A",
    desc: "Used for diagnostics like ping and traceroute.",
    img: "https://via.placeholder.com/400x250?text=ICMP",
  },
  {
    name: "ARP",
    full: "Address Resolution Protocol",
    layer: "Network",
    ports: "N/A",
    desc: "Maps IP addresses to MAC addresses.",
    img: "https://via.placeholder.com/400x250?text=ARP",
  },
  {
    name: "NAT",
    full: "Network Address Translation",
    layer: "Network",
    ports: "N/A",
    desc: "Converts private IPs to public IPs.",
    img: "https://via.placeholder.com/400x250?text=NAT",
  },
  {
    name: "BGP",
    full: "Border Gateway Protocol",
    layer: "Network",
    ports: "179",
    desc: "Core internet routing protocol between ISPs.",
    img: "https://via.placeholder.com/400x250?text=BGP",
  },
  {
    name: "OSPF",
    full: "Open Shortest Path First",
    layer: "Network",
    ports: "89",
    desc: "Interior routing protocol for fast path calculation.",
    img: "https://via.placeholder.com/400x250?text=OSPF",
  },
  {
    name: "RIP",
    full: "Routing Information Protocol",
    layer: "Network",
    ports: "520",
    desc: "Legacy routing protocol using hop count.",
    img: "https://via.placeholder.com/400x250?text=RIP",
  },

  // ================= SECURITY LAYER =================
  {
    name: "SSH",
    full: "Secure Shell",
    layer: "Security",
    ports: "22",
    desc: "Encrypted remote login protocol.",
    img: "https://via.placeholder.com/400x250?text=SSH",
  },
  {
    name: "TLS",
    full: "Transport Layer Security",
    layer: "Security",
    ports: "443",
    desc: "Encrypts data in transit between systems.",
    img: "https://via.placeholder.com/400x250?text=TLS",
  },
  {
    name: "SSL",
    full: "Secure Sockets Layer (deprecated)",
    layer: "Security",
    ports: "443",
    desc: "Older encryption protocol replaced by TLS.",
    img: "https://via.placeholder.com/400x250?text=SSL",
  },
  {
    name: "IPSec",
    full: "Internet Protocol Security",
    layer: "Security",
    ports: "500 / 4500",
    desc: "Used in VPNs for secure IP communication.",
    img: "https://via.placeholder.com/400x250?text=IPSec",
  },

  // ================= LEGACY / SPECIAL =================
  {
    name: "TELNET",
    full: "Teletype Network Protocol",
    layer: "Application",
    ports: "23",
    desc: "Unencrypted remote login protocol (obsolete).",
    img: "https://via.placeholder.com/400x250?text=TELNET",
  },
];
export default protocols;